---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netobserv-agent
  namespace: network-observability
---
kind: PodSecurityPolicy
apiVersion: policy/v1beta1
metadata:
  name: netobserv-agent
  namespace: network-observability
spec:
  privileged: true
  hostNetwork: true
  allowPrivilegeEscalation: true
  defaultAllowPrivilegeEscalation: true
  hostPID: true
  hostIPC: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  defaultAddCapabilities:
    - IPC_LOCK
    - SYS_ADMIN
    - NET_BIND_SYSTEM
    - SYS_RESOURCE
  allowedCapabilities:
    - IPC_LOCK
    - SYS_ADMIN
    - NET_BIND_SYSTEM
    - SYS_RESOURCE
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netobserv-agent
  namespace: network-observability
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
      - netobserv-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netobserv-agent
  namespace: network-observability
roleRef:
  kind: ClusterRole
  name: netobserv-agent
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Authorize all service accounts in a namespace (recommended):
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts:network-obseravbility
  - kind: ServiceAccount
    name: netobserv-agent
    namespace: network-observability
