---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netobserv-agent
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: netobserv-agent
  namespace: network-observability
allowPrivilegedContainer: true
allowHostNetwork: true
allowHostPorts: false
allowHostDirVolumePlugin: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
  - system:serviceaccount:network-observability:netobserv-agent
