
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.netobserv.io
  resources:
  - tmpdummies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.netobserv.io
  resources:
  - tmpdummies/finalizers
  verbs:
  - update
- apiGroups:
  - cache.netobserv.io
  resources:
  - tmpdummies/status
  verbs:
  - get
  - patch
  - update
